service: kevinhooketwitterbot-v2

frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  iam:
    role: ${env:ROLE}

functions:
  sendTweet:
    handler: lambda-sendtweet.handler
    events:
      # Invoke Lambda function every 2 hours
      - schedule: rate(2 hours)